Run tests on PHP 8.3 and update test suite
clue/php-socks-react pull request #113
Opened 2023-11-14 14:42 UTC by yadaiio

This pull request builds on top of #108 #107 and #105.

References: https://github.com/clue/reactphp-csv/pull/33 and others.

After this pull request is merged, we can continue with #112

2023-11-14 15:25 UTC, SimonFrings requested changes
Thanks for filing this pull request :+1: 

I added a few remarks below, should both be quick fixes.

I also noticed that the test suite currently reports unhandled promise rejections in this project (see https://github.com/reactphp/promise/pull/248 and https://github.com/orgs/reactphp/discussions/525 for reference), but I think this is something for a follow-up PR. I will look into this.

2023-11-14 15:25 UTC, SimonFrings commented on phpunit.xml.dist
> +         colors="true"
```suggestion
         cacheResult="false"
         colors="true">
```

The closing bracket here is in the wrong place, should be a quick fix.

2023-11-14 15:25 UTC, SimonFrings commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-22.04
Using `ubuntu-22.04` makes perfect sense :+1: 

It appears that we're still using the old `ubuntu-20.04` in our PHPUnit job within the `ci.yml` file. I believe this should also be updated to `ubuntu-22.04`, just like you did for the PHPUnit-hhvm job.

2023-11-14 15:59 UTC, yadaiio commented
Tysm @SimonFrings for seeing both mistakes! Helps me a lot for the future. 🥳 Should be alright now!

2023-11-14 16:02 UTC, SimonFrings approved these changes
Thanks for applying the changes, looking good :+1:

2023-11-17 16:24 UTC, clue requested changes

2023-11-17 16:24 UTC, clue commented on phpunit.xml.dist
> +         colors="true">
Should probably also include `convertDeprecationsToExceptions="true"` to fail for any deprecations as done in other projects like https://github.com/reactphp/socket/pull/277.

2024-04-24 07:15 UTC, yadaiio commented on phpunit.xml.dist
> +         colors="true">
whoops, I did change it indeed, but I forgot to resolve this conversation. Thanks @clue 👍

2024-05-27 19:40 UTC, clue approved these changes
@yadaiio Thanks for filing this PR!

I've updated the PR to no longer report any deprecations as reported in #114. This PR now no longer reports any test errors and focuses on adding PHP 8.3 only.

I'll file separate follow-up PRs to address the deprecations reported in #114 and the unhandled promise rejections reported in #115.

2024-05-27 19:40 UTC, merged

2024-05-28 06:23 UTC, yadaiio commented
Thank you @clue for the update 👍